#require File.expand_path(File.join(File.dirname(__FILE__),'..','..', '..', 'rawr', 'lib', 'rawr'))
require 'rawr'
require 'rake'

Dir.glob("tasks/**/*.rake").each do |rake_file|
  load File.expand_path(File.dirname(__FILE__) + "/" + rake_file)
end
